# Generated by Django 5.2.4 on 2025-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("details", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("guest_count", models.CharField(max_length=100)),
                ("aminities", models.CharField(max_length=500)),
                ("image", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Roomdetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.CharField(max_length=100)),
                ("guest_count", models.CharField(max_length=100)),
                ("amenities", models.TextField()),
                ("images", models.TextField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
