# Generated by Django 5.2.4 on 2025-07-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("guest_count", models.CharField(max_length=100)),
                ("aminities", models.CharField(max_length=500)),
                ("image", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
