# Generated by Django 5.2.4 on 2025-07-25 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="room_images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="Roomdetail",
        ),
        migrations.RemoveField(
            model_name="room",
            name="aminities",
        ),
        migrations.RemoveField(
            model_name="room",
            name="image",
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.TextField(default="No amenities"),
        ),
        migrations.AddField(
            model_name="room",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="room_thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AlterField(
            model_name="room",
            name="guest_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("booked", "Booked"),
                    ("unavailable", "Unavailable"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="myapp.room",
            ),
        ),
    ]
