# Generated by Django 5.2.4 on 2025-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_roomimage_delete_feature_delete_roomdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
