# Generated by Django 5.2.4 on 2025-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="roomdetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.CharField(max_length=100)),
                ("guest_count", models.CharField(max_length=100)),
                ("amenities", models.TextField()),
                ("images", models.TextField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
