# Generated by Django 5.2.4 on 2025-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_room_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="No description")),
                ("price", models.PositiveIntegerField(default=0)),
                ("badge", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="food_thumnail/"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("non-vegetarian", "Non-Vegetarian"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
