# Generated by Django 5.2.4 on 2025-08-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rooms", "Rooms"),
                            ("resturant", "resturant"),
                            ("resturant", "resturant"),
                            ("resturant", "resturant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery_images/"
                    ),
                ),
            ],
        ),
    ]
