# Generated by Django 5.2.4 on 2025-08-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_image_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="category",
            field=models.CharField(
                choices=[
                    ("rooms", "Rooms"),
                    ("resturant", "Resturant"),
                    ("lobby", "Lobby"),
                    ("facilities", "Facilities"),
                    ("events", "Events"),
                ],
                max_length=50,
            ),
        ),
    ]
